<?php


include_once("view_controller/ctrl.php");


class index_ctrl extends view_controller {
    public function __construct()
    {
        $this -> child_ctrl = array();
    }


    public function getParentCtrl()
    {
        return null; // TODO: Change the autogenerated stub
    }


}