
<?php


include_once("view_controller/ctrl.php");


class headbar_ctrl extends view_controller {
    function get_html($tag)
    {

        return parent::get_html($tag); // TODO: Change the autogenerated stub
    }

}