<?php


include_once("controller/ctrl.php");

class body_ctrl extends controller {
    function get_html($tag)

    {

        return "<body>" . parent::get_html($tag) . "</body>"; // TODO: Change the autogenerated stub
    }

}