<?php


include_once("controller/ctrl.php");


class index_ctrl extends controller {

    function get_html()
    {
        echo "<html>".parent::get_html()."</html>"; // TODO: Change the autogenerated stub
    }
}