
<?php


include_once("controller/ctrl.php");


class headbar_ctrl extends controller {
    function get_html($tag)
    {

        return parent::get_html($tag); // TODO: Change the autogenerated stub
    }

}